### ISSUE TITLE
是否需要个神奇版本的chrome? WebDriverException: Message: disconnected: unable to connect to renderer

### ISSUE THREAD

**Issue by qiudaomao** [EvilCult/moviecatcher#4]
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk/Tkinter.py", line 1541, in __call__
    return self.func(*args)
  File "../View/MenuBarView.py", line 42, in <lambda>
    editMenu.add_command(label = "Baidu Login", command = lambda cb = BdApi.BdApi().saveLogin : PlayerView.GUI(self.master).showLoginWindow(cb))
  File "../View/PlayerView.py", line 124, in showLoginWindow
    self.browser.maximize_window()
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 640, in maximize_window
    self.execute(command, {"windowHandle": "current"})
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: disconnected: unable to connect to renderer
  (Session info: chrome=63.0.3223.8)
  (Driver info: chromedriver=2.32.498537 (cb2f855cbc7b82e20387eaf9a43f6b99b6105061),platform=Mac OS X 10.13.0 x86_64)

**Comment by EvilCult** [comment]
嗯，这是个好问题。让我想想如何甩锅。。。。。。

你的Chrome浏览器版本是「63.0.3223.8」，太高了。。。
最新的Chromedriver版本是2.32。只支持Chrome59-61。[见此](http://chromedriver.storage.googleapis.com/2.32/notes.txt)
至于为什么Google自己出的最新的Driver不支持自己最新的浏览器。。。我也是。。（手动黑人问号）

解决方法是降级Chrome，或者等新的Driver。不过鉴于dalao已经在自己执行了，最快捷的方式应该是改两行代码，换FirefoxDriver（手动捂脸）

**Comment by qiudaomao** [comment]
降到61可以用了，赞！
